'use strict';
/* Labelled, synthetic tool events for evaluating Focus classification.

   Each case gives the tool call an agent makes and what a reviewer would expect Focus to record:
   the stage, any recognised check, the areas that must be signalled (`areas`) and the areas that
   must not be (`not`). Areas not listed either way are unjudged. Labels follow the category
   meanings in src/focus-areas.json and docs/DESIGN.md, not the current classifier's output.
   Paths and commands are invented; no real project, person or transcript is represented. */
const bash = (command, extra = {}) => ({ tool: 'Bash', input: { command }, ...extra });
const edit = (file_path, extra = {}) => ({ tool: 'Edit', input: { file_path }, ...extra });
const read = (file_path, extra = {}) => ({ tool: 'Read', input: { file_path }, ...extra });
const cases = [
  // Claude Code file tools
  [
    'read auth session',
    read('server/auth/session.ts'),
    'Inspected',
    null,
    ['security'],
    ['performance'],
  ],
  [
    'grep inside auth',
    { tool: 'Grep', input: { pattern: 'token', path: 'src/auth' } },
    'Inspected',
    null,
    ['security'],
    [],
  ],
  [
    'glob for tests',
    { tool: 'Glob', input: { pattern: '**/*.test.ts' } },
    'Inspected',
    null,
    ['testing'],
    ['security'],
  ],
  [
    'notebook edit',
    { tool: 'NotebookEdit', input: { notebook_path: 'notebooks/forecast_model.ipynb' } },
    'Changed',
    null,
    ['data'],
    ['ux'],
  ],
  [
    'login form component',
    edit('components/auth/LoginForm.tsx'),
    'Changed',
    null,
    ['ux', 'security'],
    ['data'],
  ],
  [
    'route group sign-in page',
    edit('app/(auth)/sign-in/page.tsx'),
    'Changed',
    null,
    ['ux', 'security'],
    [],
  ],
  [
    'camelCase auth hook',
    { tool: 'Write', input: { file_path: 'src/hooks/useAuth.ts' } },
    'Changed',
    null,
    ['security'],
    ['performance'],
  ],
  [
    'rate limit middleware',
    edit('server/middleware/rateLimit.ts'),
    'Changed',
    null,
    ['security', 'backend'],
    [],
  ],
  [
    'RLS migration',
    edit('supabase/migrations/20260927_rls_policies.sql'),
    'Changed',
    null,
    ['data', 'security'],
    [],
  ],
  ['env example', edit('.env.example'), 'Changed', null, ['delivery'], ['security']],
  ['dockerfile', edit('Dockerfile'), 'Changed', null, ['delivery'], []],
  ['CI workflow', edit('.github/workflows/ci.yml'), 'Changed', null, ['delivery'], []],
  [
    'package manifest',
    edit('package.json'),
    'Changed',
    null,
    ['delivery'],
    ['security', 'product'],
  ],
  ['lockfile', edit('package-lock.json'), 'Changed', null, [], ['reliability', 'security']],
  ['readme', read('README.md'), 'Inspected', null, ['docs'], []],
  ['contributing guide', edit('CONTRIBUTING.md'), 'Changed', null, ['docs'], ['backend']],
  ['docs page', edit('docs/SCORING.md'), 'Changed', null, ['docs'], []],
  ['changelog', edit('CHANGELOG.md'), 'Changed', null, ['docs'], []],
  ['security policy doc', edit('SECURITY.md'), 'Changed', null, ['security', 'docs'], []],
  ['licence', edit('LICENSE'), 'Changed', null, ['privacy'], []],
  ['agent instructions', edit('AGENTS.md'), 'Changed', null, ['docs'], ['backend']],
  ['data table component', edit('src/components/DataTable.tsx'), 'Changed', null, ['ux'], ['data']],
  [
    'compute helper',
    edit('src/lib/computeTotals.ts'),
    'Changed',
    null,
    ['backend'],
    ['performance'],
  ],
  ['lru cache', edit('src/cache/lru.ts'), 'Changed', null, ['performance'], ['security']],
  [
    'payment retry',
    edit('services/payments/retry.ts'),
    'Changed',
    null,
    ['reliability', 'backend'],
    ['testing'],
  ],
  ['dead letter queue', edit('src/queue/deadLetter.ts'), 'Changed', null, ['reliability'], []],
  [
    'idempotency key',
    edit('src/api/idempotencyKey.ts'),
    'Changed',
    null,
    ['reliability', 'backend'],
    [],
  ],
  [
    'error boundary',
    edit('lib/errors/ErrorBoundary.tsx'),
    'Changed',
    null,
    ['ux', 'reliability'],
    [],
  ],
  ['e2e checkout spec', edit('tests/e2e/checkout.spec.ts'), 'Changed', null, ['testing'], []],
  ['e2e login spec', edit('e2e/login.spec.ts'), 'Changed', null, ['testing', 'security'], []],
  ['cypress spec', edit('cypress/e2e/cart.cy.ts'), 'Changed', null, ['testing'], []],
  [
    'jest snapshot',
    edit('src/__snapshots__/Button.test.tsx.snap'),
    'Changed',
    null,
    ['testing'],
    [],
  ],
  ['rspec model spec', edit('spec/models/user_spec.rb'), 'Changed', null, ['testing'], []],
  [
    'java test class',
    edit('src/test/java/com/acme/OrderServiceTest.java'),
    'Changed',
    null,
    ['testing'],
    [],
  ],
  ['swift tests', edit('Tests/AppTests/LoginTests.swift'), 'Changed', null, ['testing'], []],
  ['conftest', edit('conftest.py'), 'Changed', null, ['testing'], []],
  ['vitest config', edit('vitest.config.ts'), 'Changed', null, ['testing'], []],
  [
    'product spec is not a test',
    edit('product/spec.md'),
    'Changed',
    null,
    ['product'],
    ['testing', 'docs'],
  ],
  ['PRD', edit('docs/prd/checkout-redesign.md'), 'Changed', null, ['product', 'docs'], ['testing']],
  [
    'literature review',
    read('research/literature-review.md'),
    'Inspected',
    null,
    [],
    ['product', 'docs'],
  ],
  ['analytics events', edit('src/analytics/events.ts'), 'Changed', null, ['analytics'], []],
  ['posthog client', edit('src/lib/posthog.ts'), 'Changed', null, ['analytics'], []],
  [
    'telemetry is not analytics',
    edit('observability/telemetry.ts'),
    'Changed',
    null,
    ['delivery'],
    ['analytics'],
  ],
  ['logger', edit('src/lib/logger.ts'), 'Changed', null, ['delivery'], ['analytics']],
  ['consent banner', edit('src/privacy/ConsentBanner.tsx'), 'Changed', null, ['privacy', 'ux'], []],
  ['gdpr export', edit('src/gdpr/dataExport.ts'), 'Changed', null, ['privacy'], []],
  ['pii redaction', edit('src/pii/redact.ts'), 'Changed', null, ['privacy'], []],
  [
    'auth session is not performance',
    edit('server/auth/session.ts'),
    'Changed',
    null,
    ['security'],
    ['performance'],
  ],
  [
    'tokenizer is not security',
    edit('src/lib/tokenizer.ts'),
    'Changed',
    null,
    ['backend'],
    ['security'],
  ],
  [
    'design tokens are not security',
    edit('styles/design-tokens.css'),
    'Changed',
    null,
    ['ux'],
    ['security'],
  ],
  [
    'keyboard shortcuts are not security',
    edit('src/keyboard/shortcuts.ts'),
    'Changed',
    null,
    [],
    ['security'],
  ],
  ['chat session is not security', edit('src/chat/session.ts'), 'Changed', null, [], ['security']],
  ['encryption helper', edit('src/crypto/encrypt.ts'), 'Changed', null, ['security'], []],
  ['oauth callback', edit('src/auth/oauth/callback.ts'), 'Changed', null, ['security'], []],
  ['content security policy', edit('src/security/csp.ts'), 'Changed', null, ['security'], []],
  ['cors config', edit('config/cors.ts'), 'Changed', null, ['security'], []],
  ['html sanitiser', edit('src/lib/sanitizeHtml.ts'), 'Changed', null, ['security'], []],
  ['terraform iam', edit('infra/terraform/iam.tf'), 'Changed', null, ['delivery', 'security'], []],
  ['k8s deployment', edit('k8s/deployment.yaml'), 'Changed', null, ['delivery'], []],
  ['helm values', edit('helm/charts/api/values.yaml'), 'Changed', null, ['delivery'], []],
  ['firmware driver', edit('firmware/drivers/i2c.c'), 'Changed', null, ['backend'], ['privacy']],
  ['ml training', edit('training/models/forecast.py'), 'Changed', null, ['data'], []],
  ['db queries', edit('src/db/queries.ts'), 'Changed', null, ['data'], []],
  ['prisma schema', edit('prisma/schema.prisma'), 'Changed', null, ['data'], []],
  ['server router', edit('src/server/routers/orders.ts'), 'Changed', null, ['backend'], []],
  ['api route', edit('src/app/api/orders/route.ts'), 'Changed', null, ['backend'], []],
  ['go main', edit('cmd/server/main.go'), 'Changed', null, ['backend'], []],
  ['rust parser', edit('src/parser.rs'), 'Changed', null, ['backend'], ['testing']],
  ['virtual list', edit('src/perf/virtualList.tsx'), 'Changed', null, ['performance', 'ux'], []],
  ['benchmarks folder', edit('benchmarks/parse.bench.ts'), 'Changed', null, ['performance'], []],
  ['adr', edit('docs/adr/0003-queue.md'), 'Changed', null, ['architecture', 'docs'], []],
  ['architecture doc', edit('ARCHITECTURE.md'), 'Changed', null, ['architecture'], []],
  ['eslint config', edit('eslint.config.js'), 'Changed', null, ['architecture'], []],
  ['biome config', edit('biome.json'), 'Changed', null, ['architecture'], []],
  ['prettier config', edit('.prettierrc.json'), 'Changed', null, ['architecture'], []],
  ['translations', edit('src/i18n/en.json'), 'Changed', null, ['ux'], []],
  ['locales', edit('locales/ms/common.json'), 'Changed', null, ['ux'], []],
  ['stylesheet', edit('media/view.css'), 'Changed', null, ['ux'], []],
  [
    'dependency source is ignored',
    read('node_modules/react/index.js'),
    'Inspected',
    null,
    [],
    ['backend', 'ux'],
  ],
  ['build output is ignored', read('dist/extension.js'), 'Inspected', null, [], ['backend']],
  [
    'outside folder names make no claim',
    read('/Users/demo/security-review/notes/plan.md'),
    'Inspected',
    null,
    [],
    ['security'],
  ],
  ['requirements.txt is dependencies', edit('requirements.txt'), 'Changed', null, [], ['product']],
  ['e-commerce product model', edit('src/models/product.ts'), 'Changed', null, [], ['product']],
  [
    'agent memory is not performance',
    edit('src/agents/memory.ts'),
    'Changed',
    null,
    [],
    ['performance'],
  ],
  [
    'type conversion is not analytics',
    edit('src/utils/typeConversion.ts'),
    'Changed',
    null,
    [],
    ['analytics'],
  ],
  [
    'dependency injection is not security',
    edit('src/di/injection.ts'),
    'Changed',
    null,
    [],
    ['security'],
  ],
  ['aria roles are not security', edit('src/a11y/roles.ts'), 'Changed', null, ['ux'], ['security']],
  [
    'keyboard navigation',
    edit('components/a11y/keyboard-navigation.tsx'),
    'Changed',
    null,
    ['ux'],
    [],
  ],
  [
    'cookie consent is privacy',
    edit('src/cookies/consent.ts'),
    'Changed',
    null,
    ['privacy'],
    ['security'],
  ],

  // Shell commands
  ['npm test', bash('npm test'), 'Check run', 'test', ['testing'], ['reliability']],
  ['cd then test', bash('cd platform && npm test'), 'Check run', 'test', ['testing'], []],
  ['test piped to tail', bash('npm test 2>&1 | tail -40'), 'Check run', 'test', ['testing'], []],
  [
    'vitest scoped',
    bash('npx vitest run src/auth'),
    'Check run',
    'test',
    ['testing', 'security'],
    [],
  ],
  ['pnpm filter test', bash('pnpm --filter web test'), 'Check run', 'test', ['testing'], []],
  ['yarn workspace test', bash('yarn workspace api test'), 'Check run', 'test', ['testing'], []],
  [
    'python -m pytest',
    bash('python -m pytest tests/test_auth.py -q'),
    'Check run',
    'test',
    ['testing', 'security'],
    [],
  ],
  ['uv run pytest', bash('uv run pytest'), 'Check run', 'test', ['testing'], []],
  ['go test', bash('go test ./...'), 'Check run', 'test', ['testing'], []],
  [
    'bundle exec rspec',
    bash('bundle exec rspec spec/models/user_spec.rb'),
    'Check run',
    'test',
    ['testing'],
    [],
  ],
  ['gradlew test', bash('./gradlew test'), 'Check run', 'test', ['testing'], []],
  ['mvn test', bash('mvn -q test'), 'Check run', 'test', ['testing'], []],
  ['make test', bash('make test'), 'Check run', 'test', ['testing'], []],
  [
    'playwright test',
    bash('npx playwright test e2e/login.spec.ts'),
    'Check run',
    'test',
    ['testing', 'security'],
    [],
  ],
  ['env then test', bash('CI=1 npm test'), 'Check run', 'test', ['testing'], []],
  ['timeout test', bash('timeout 120 npm test'), 'Check run', 'test', ['testing'], []],
  ['shell -c wrapper', bash('bash -lc "npm test"'), 'Check run', 'test', ['testing'], []],
  ['node test runner', bash('node --test test/*.test.js'), 'Check run', 'test', ['testing'], []],
  // The more specific kind wins: an accessibility test run is an accessibility check.
  [
    'accessibility test script',
    bash('npm run test:a11y'),
    'Check run',
    'accessibility',
    ['testing', 'ux'],
    [],
  ],
  [
    'npm run lint',
    bash('npm run lint'),
    'Check run',
    'static',
    ['architecture'],
    ['testing', 'reliability'],
  ],
  ['tsc', bash('npx tsc --noEmit'), 'Check run', 'static', ['architecture'], []],
  ['type-check script', bash('npm run type-check'), 'Check run', 'static', ['architecture'], []],
  ['prettier check', bash('npx prettier --check .'), 'Check run', 'static', ['architecture'], []],
  ['prettier write', bash('npx prettier --write src/'), 'Changed', null, ['architecture'], []],
  ['ruff', bash('ruff check .'), 'Check run', 'static', ['architecture'], []],
  ['clippy', bash('cargo clippy -- -D warnings'), 'Check run', 'static', ['architecture'], []],
  ['go vet', bash('go vet ./...'), 'Check run', 'static', ['architecture'], []],
  ['npm audit', bash('npm audit --omit=dev'), 'Check run', 'security', ['security'], []],
  ['pip-audit', bash('pip-audit'), 'Check run', 'security', ['security'], []],
  ['semgrep', bash('semgrep --config auto'), 'Check run', 'security', ['security'], []],
  ['gitleaks', bash('gitleaks detect'), 'Check run', 'security', ['security'], []],
  ['cargo audit', bash('cargo audit'), 'Check run', 'security', ['security'], []],
  ['npm run bench', bash('npm run bench'), 'Check run', 'benchmark', ['performance'], ['security']],
  ['pnpm benchmark', bash('pnpm benchmark'), 'Check run', 'benchmark', ['performance'], []],
  ['cargo bench', bash('cargo bench'), 'Check run', 'benchmark', ['performance'], []],
  ['hyperfine', bash("hyperfine 'node a.js'"), 'Check run', 'benchmark', ['performance'], []],
  ['k6', bash('k6 run load/checkout.js'), 'Check run', 'benchmark', ['performance'], []],
  [
    'lighthouse',
    bash('npx lighthouse http://localhost:3000'),
    'Check run',
    'benchmark',
    ['performance'],
    [],
  ],
  ['pa11y', bash('npx pa11y http://localhost:3000'), 'Check run', 'accessibility', ['ux'], []],
  ['npm run build', bash('npm run build'), 'Check run', 'build', ['delivery'], []],
  ['docker build', bash('docker build -t app .'), 'Check run', 'build', ['delivery'], []],
  ['terraform plan', bash('terraform plan'), 'Command run', null, ['delivery'], []],
  [
    'kubectl apply',
    bash('kubectl apply -f k8s/deployment.yaml'),
    'Command run',
    null,
    ['delivery'],
    [],
  ],
  ['psql migration', bash('psql -f migrations/001_init.sql'), 'Command run', null, ['data'], []],
  ['prisma migrate', bash('npx prisma migrate dev'), 'Changed', null, ['data'], []],
  ['git diff', bash('git diff src/auth/session.ts'), 'Inspected', null, ['security'], []],
  ['git status', bash('git status'), 'Inspected', null, [], ['security', 'backend']],
  [
    'git commit message is ignored',
    bash('git commit -m "fix auth"'),
    'Command run',
    null,
    [],
    ['security'],
  ],
  [
    'heredoc write',
    bash("cat > docs/guide.md <<'EOF'\nSee server/auth/session.ts\nEOF"),
    'Changed',
    null,
    ['docs'],
    ['security'],
  ],
  ['sed in place', bash("sed -i 's/a/b/' src/cache/lru.ts"), 'Changed', null, ['performance'], []],
  ['sed print', bash("sed -n '1,80p' src/auth/session.ts"), 'Inspected', null, ['security'], []],
  ['rm file', bash('rm -rf src/legacy/oldAuth.ts'), 'Changed', null, ['security'], []],
  ['echo redirect', bash('echo "hello" > notes.txt'), 'Changed', null, [], ['security']],
  [
    'bare echo keywords',
    bash('echo security performance'),
    'Command run',
    null,
    [],
    ['security', 'performance'],
  ],
  ['echoed path', bash('echo server/auth/session.ts'), 'Command run', null, [], ['security']],
  ['rg quoted pattern', bash('rg -n "password" src'), 'Inspected', null, [], ['security']],
  ['rg in auth', bash('rg session src/auth'), 'Inspected', null, ['security'], []],
  ['cat lint keyword', bash('cat lint'), 'Inspected', null, [], ['architecture', 'testing']],
  ['rg test keyword', bash('rg test src'), 'Inspected', null, [], ['testing']],
  [
    'quoted route group path',
    bash('cat "app/(auth)/sign-in/page.tsx"'),
    'Inspected',
    null,
    ['security', 'ux'],
    [],
  ],
  [
    'python inline code',
    bash(`python -c 'print("/private/secret.py")'`),
    'Command run',
    null,
    [],
    ['security'],
  ],
  [
    'test then read',
    bash('npm test && cat server/auth/session.ts'),
    'Check run',
    'test',
    ['testing', 'security'],
    [],
  ],
  ['npm run dev', bash('npm run dev'), 'Command run', null, [], ['testing', 'delivery']],
  ['install dependency', bash('npm install zod'), 'Changed', null, ['architecture'], ['security']],
  [
    'failing test run',
    bash('npm test', { response: { exit_code: 1 } }),
    'Check failed',
    'test',
    ['testing'],
    [],
  ],
  [
    'failing read',
    bash('cat server/auth/session.ts', { response: { exit_code: 1 } }),
    'Tool failed',
    null,
    [],
    ['security'],
  ],
  [
    'failed edit',
    edit('server/auth/session.ts', { kind: 'PostToolUseFailure' }),
    'Tool failed',
    null,
    [],
    ['security'],
  ],

  // Codex
  [
    'codex argv shell',
    { tool: 'shell', input: { command: ['bash', '-lc', 'cd web && npm run lint'] } },
    'Check run',
    'static',
    ['architecture'],
    [],
  ],
  [
    'codex exec_command',
    { tool: 'exec_command', input: { cmd: 'cargo test' } },
    'Check run',
    'test',
    ['testing'],
    [],
  ],
  [
    'codex patch',
    {
      tool: 'apply_patch',
      input: '*** Begin Patch\n*** Update File: server/auth/session.ts\n+x\n*** End Patch',
    },
    'Changed',
    null,
    ['security'],
    ['performance'],
  ],
  [
    'codex view image',
    { tool: 'view_image', input: { path: 'docs/images/focus.png' } },
    'Inspected',
    null,
    [],
    ['security'],
  ],

  // Cursor
  [
    'cursor shell',
    { tool: 'Bash', input: { command: 'npm test' } },
    'Check run',
    'test',
    ['testing'],
    [],
  ],
  [
    'cursor edit_file',
    { tool: 'edit_file', input: { target_file: 'src/auth/login.ts' } },
    'Changed',
    null,
    ['security'],
    [],
  ],
  [
    'cursor read_file',
    { tool: 'read_file', input: { target_file: 'src/components/Nav.tsx' } },
    'Inspected',
    null,
    ['ux'],
    [],
  ],
  [
    'cursor delete',
    { tool: 'delete_file', input: { target_file: 'src/old.ts' } },
    'Changed',
    null,
    [],
    [],
  ],
  [
    'cursor search_replace',
    { tool: 'search_replace', input: { file_path: 'src/db/schema.ts' } },
    'Changed',
    null,
    ['data'],
    [],
  ],
  [
    'cursor codebase search',
    { tool: 'codebase_search', input: { query: 'auth flow' } },
    'Inspected',
    null,
    [],
    ['security'],
  ],

  // MCP and other tools
  [
    'mcp write file',
    { tool: 'mcp__filesystem__write_file', input: { path: 'src/auth/x.ts' } },
    'Changed',
    null,
    ['security'],
    [],
  ],
  [
    'mcp read docs',
    { tool: 'mcp__filesystem__read_text_file', input: { path: 'docs/intro.md' } },
    'Inspected',
    null,
    ['docs'],
    [],
  ],
  [
    'mcp sql',
    { tool: 'mcp__supabase__execute_sql', input: { query: 'select 1' } },
    'Tool used',
    null,
    ['data'],
    ['backend'],
  ],
  [
    'mcp browser snapshot',
    { tool: 'mcp__playwright__browser_snapshot', input: {} },
    'Inspected',
    null,
    ['ux'],
    ['testing'],
  ],
  [
    'mcp issue tracker',
    { tool: 'mcp__linear__create_issue', input: { title: 'Fix auth' } },
    'Tool used',
    null,
    [],
    ['security', 'backend'],
  ],
  [
    'web search',
    { tool: 'WebSearch', input: { query: 'oauth pkce' } },
    'Tool used',
    null,
    [],
    ['security'],
  ],

  // Written after the vocabulary above was tuned and scored once before any further change,
  // as a held-out estimate. They now guard against regressions like the rest.

  [
    'django auth views',
    edit('accounts/views/password_reset.py'),
    'Changed',
    null,
    ['security'],
    [],
  ],
  [
    'rails controller',
    edit('app/controllers/orders_controller.rb'),
    'Changed',
    null,
    ['backend'],
    [],
  ],
  ['vue component', edit('src/views/CheckoutPage.vue'), 'Changed', null, ['ux'], ['data']],
  ['svelte store', edit('src/lib/stores/cart.ts'), 'Changed', null, [], ['security']],
  [
    'kotlin viewmodel',
    edit('app/src/main/java/com/shop/ui/ProfileViewModel.kt'),
    'Changed',
    null,
    ['ux'],
    ['data'],
  ],
  ['swiftui screen', edit('Sources/App/Screens/SettingsScreen.swift'), 'Changed', null, ['ux'], []],
  ['flutter widget', edit('lib/widgets/order_card.dart'), 'Changed', null, ['ux'], []],
  ['graphql resolver', edit('src/graphql/resolvers/user.ts'), 'Changed', null, ['backend'], []],
  ['alembic migration', edit('alembic/versions/3f2a_add_orders.py'), 'Changed', null, ['data'], []],
  ['dbt model', edit('models/marts/fct_orders.sql'), 'Changed', null, ['data'], []],
  ['airflow dag', edit('dags/daily_ingest.py'), 'Changed', null, ['data'], []],
  ['jwt verify', edit('src/middleware/verifyJwt.ts'), 'Changed', null, ['security', 'backend'], []],
  ['password hashing', edit('src/lib/hashPassword.ts'), 'Changed', null, ['security'], []],
  [
    'secrets manager',
    edit('infra/secrets/vault.tf'),
    'Changed',
    null,
    ['security', 'delivery'],
    [],
  ],
  ['nginx conf', edit('deploy/nginx/site.conf'), 'Changed', null, ['delivery'], []],
  ['github action', edit('.github/workflows/release.yml'), 'Changed', null, ['delivery'], []],
  ['sentry init', edit('src/instrument/sentry.ts'), 'Changed', null, ['delivery'], ['analytics']],
  ['prometheus rules', edit('monitoring/alerts/rules.yml'), 'Changed', null, ['delivery'], []],
  ['retry backoff util', edit('pkg/httpclient/backoff.go'), 'Changed', null, ['reliability'], []],
  [
    'circuit breaker',
    edit('src/resilience/circuitBreaker.ts'),
    'Changed',
    null,
    ['reliability'],
    [],
  ],
  [
    'health check endpoint',
    edit('src/routes/healthcheck.ts'),
    'Changed',
    null,
    ['reliability'],
    [],
  ],
  [
    'memoised selector',
    edit('src/state/selectors/memoizedTotals.ts'),
    'Changed',
    null,
    ['performance'],
    [],
  ],
  [
    'image lazy loading',
    edit('src/components/LazyImage.tsx'),
    'Changed',
    null,
    ['ux', 'performance'],
    [],
  ],
  [
    'web vitals report',
    edit('src/reportWebVitals.ts'),
    'Changed',
    null,
    ['performance'],
    ['analytics'],
  ],
  ['amplitude tracking', edit('src/tracking/amplitude.ts'), 'Changed', null, ['analytics'], []],
  [
    'funnel dashboard sql',
    edit('analytics/funnels/signup_funnel.sql'),
    'Changed',
    null,
    ['analytics', 'data'],
    [],
  ],
  [
    'cookie policy page',
    edit('content/legal/cookie-policy.md'),
    'Changed',
    null,
    ['privacy'],
    ['security'],
  ],
  ['data retention job', edit('jobs/dataRetention.ts'), 'Changed', null, ['privacy'], []],
  ['hipaa notes', edit('compliance/hipaa-controls.md'), 'Changed', null, ['privacy'], []],
  ['roadmap', edit('planning/roadmap-2027.md'), 'Changed', null, ['product'], ['testing']],
  ['user stories', edit('docs/user-stories/checkout.md'), 'Changed', null, ['product', 'docs'], []],
  ['api reference docs', edit('docs/api-reference/orders.md'), 'Changed', null, ['docs'], []],
  [
    'storybook story',
    edit('src/components/Button.stories.tsx'),
    'Changed',
    null,
    ['ux'],
    ['testing'],
  ],
  ['pytest fixture file', edit('tests/fixtures/users.json'), 'Changed', null, ['testing'], []],
  [
    'go test file',
    edit('internal/cache/lru_test.go'),
    'Changed',
    null,
    ['testing', 'performance'],
    [],
  ],
  ['junit test', edit('src/test/kotlin/PaymentServiceTest.kt'), 'Changed', null, ['testing'], []],
  ['refactor folder', edit('src/legacy/refactor-notes.md'), 'Changed', null, ['architecture'], []],
  ['golangci config', edit('.golangci.yml'), 'Changed', null, ['architecture'], []],
  ['sbom', edit('sbom/cyclonedx.json'), 'Changed', null, ['security'], []],
  [
    'vendor code ignored',
    read('vendor/github.com/lib/pq/conn.go'),
    'Inspected',
    null,
    [],
    ['data', 'backend'],
  ],
  ['pnpm vitest', bash('pnpm vitest run tests/unit'), 'Check run', 'test', ['testing'], []],
  [
    'yarn jest watch',
    bash('yarn jest --watch=false src/utils'),
    'Check run',
    'test',
    ['testing'],
    [],
  ],
  ['poetry pytest', bash('poetry run pytest -k auth'), 'Check run', 'test', ['testing'], []],
  ['dotnet test', bash('dotnet test ./Api.Tests'), 'Check run', 'test', ['testing'], []],
  ['swift test', bash('swift test'), 'Check run', 'test', ['testing'], []],
  ['flutter analyze', bash('flutter analyze'), 'Check run', 'static', ['architecture'], []],
  [
    'eslint dir',
    bash('npx eslint src --max-warnings=0'),
    'Check run',
    'static',
    ['architecture'],
    [],
  ],
  ['mypy strict', bash('mypy --strict app/'), 'Check run', 'static', ['architecture'], []],
  ['trivy image', bash('trivy image myapp:latest'), 'Check run', 'security', ['security'], []],
  ['govulncheck', bash('govulncheck ./...'), 'Check run', 'security', ['security'], []],
  ['bandit', bash('bandit -r app/'), 'Check run', 'security', ['security'], []],
  [
    'autocannon',
    bash('npx autocannon -c 100 http://localhost:3000/api'),
    'Check run',
    'benchmark',
    ['performance'],
    [],
  ],
  [
    'go bench',
    bash('go test -bench=. -benchmem ./internal/cache'),
    'Check run',
    'benchmark',
    ['performance'],
    [],
  ],
  ['vite build', bash('npx vite build'), 'Check run', 'build', ['delivery'], []],
  ['cargo build release', bash('cargo build --release'), 'Check run', 'build', ['delivery'], []],
  [
    'helm upgrade',
    bash('helm upgrade --install api ./charts/api'),
    'Command run',
    null,
    ['delivery'],
    [],
  ],
  ['docker compose up', bash('docker compose up -d db'), 'Command run', null, ['delivery'], []],
  ['sqlite query', bash('sqlite3 data/app.db ".tables"'), 'Command run', null, ['data'], []],
  ['head of file', bash('head -n 50 src/auth/tokens.ts'), 'Inspected', null, ['security'], []],
  ['grep recursive', bash('grep -rn "TODO" src/payments'), 'Inspected', null, [], ['security']],
  [
    'find tests',
    bash('find . -name "*.spec.ts" -not -path "./node_modules/*"'),
    'Inspected',
    null,
    [],
    ['security'],
  ],
  ['mkdir feature', bash('mkdir -p src/features/billing/components'), 'Changed', null, ['ux'], []],
  [
    'mv to archive',
    bash('mv src/old/Login.tsx src/archive/Login.tsx'),
    'Changed',
    null,
    ['ux', 'security'],
    [],
  ],
  ['tee config', bash('echo "x" | tee config/settings.yml'), 'Changed', null, [], ['security']],
  [
    'piped test through grep',
    bash('pytest -q 2>&1 | grep -E "passed|failed"'),
    'Check run',
    'test',
    ['testing'],
    [],
  ],
  [
    'subshell lint',
    bash('(cd packages/web && pnpm lint)'),
    'Check run',
    'static',
    ['architecture'],
    [],
  ],
  ['make with var', bash('make CI=1 lint'), 'Check run', 'static', ['architecture'], []],
  ['nx affected test', bash('npx nx affected -t test'), 'Check run', 'test', ['testing'], []],
  ['turbo build', bash('npx turbo run build --filter=web'), 'Check run', 'build', ['delivery'], []],
  [
    'git log path',
    bash('git log --oneline -5 -- src/billing/invoice.ts'),
    'Inspected',
    null,
    [],
    ['security'],
  ],
  [
    'curl api',
    bash('curl -s http://localhost:3000/api/health'),
    'Command run',
    null,
    [],
    ['security', 'testing'],
  ],
  [
    'cursor list_dir',
    { tool: 'list_dir', input: { relative_workspace_path: 'src/components' } },
    'Inspected',
    null,
    ['ux'],
    [],
  ],
  [
    'cursor grep',
    { tool: 'grep', input: { pattern: 'useQuery', path: 'src/hooks' } },
    'Inspected',
    null,
    [],
    ['security'],
  ],
  [
    'mcp github file',
    { tool: 'mcp__github__get_file_contents', input: { path: 'src/auth/session.ts' } },
    'Inspected',
    null,
    ['security'],
    [],
  ],
  [
    'mcp figma',
    { tool: 'mcp__figma__get_design_context', input: { nodeId: '1:2' } },
    'Tool used',
    null,
    ['ux'],
    [],
  ],
  [
    'todo write',
    { tool: 'TodoWrite', input: { todos: [{ content: 'Add tests' }] } },
    'Planned',
    null,
    [],
    ['testing'],
  ],

  // Project stakes. Production and critical vocabulary is inert at lower stakes; a sensitive change
  // needs a changed, non-test, non-document workspace file with strong evidence of its kind.
  [
    'ledger at standard',
    edit('src/ledger/postEntry.ts'),
    'Changed',
    null,
    ['backend'],
    ['data'],
    { stakes: 'standard', sensitive: null },
  ],
  [
    'ledger at production',
    edit('src/ledger/postEntry.ts'),
    'Changed',
    null,
    ['data'],
    [],
    { stakes: 'production', sensitive: 'payments or money movement' },
  ],
  [
    'migration marked',
    edit('db/migrations/002_add_index.sql'),
    'Changed',
    null,
    ['data'],
    [],
    { stakes: 'production', sensitive: 'database migration or schema' },
  ],
  [
    'migration at standard is not marked',
    edit('db/migrations/002_add_index.sql'),
    'Changed',
    null,
    ['data'],
    [],
    { stakes: 'standard', sensitive: null },
  ],
  [
    'migration test not marked',
    edit('tests/migrations/002.test.ts'),
    'Changed',
    null,
    ['testing'],
    [],
    { stakes: 'production', sensitive: null },
  ],
  [
    'auth document not marked',
    edit('docs/auth.md'),
    'Changed',
    null,
    ['docs'],
    [],
    { stakes: 'production', sensitive: null },
  ],
  [
    'auth read not marked',
    read('src/auth/session.ts'),
    'Inspected',
    null,
    ['security'],
    [],
    { stakes: 'production', sensitive: null },
  ],
  [
    'auth change marked',
    edit('src/auth/session.ts'),
    'Changed',
    null,
    ['security'],
    [],
    { stakes: 'production', sensitive: 'authentication or access control' },
  ],
  [
    'production secrets marked',
    edit('.env.production'),
    'Changed',
    null,
    ['delivery'],
    [],
    { stakes: 'production', sensitive: 'secrets or credentials' },
  ],
  [
    'deploy workflow marked',
    edit('.github/workflows/deploy.yml'),
    'Changed',
    null,
    ['delivery'],
    [],
    { stakes: 'production', sensitive: 'deployment or infrastructure' },
  ],
  [
    'checkout button is not money',
    edit('src/components/CheckoutButton.tsx'),
    'Changed',
    null,
    ['ux'],
    ['data'],
    { stakes: 'production', sensitive: null },
  ],
  [
    'tenant isolation',
    edit('src/tenancy/tenantIsolation.ts'),
    'Changed',
    null,
    ['security'],
    [],
    { stakes: 'production', sensitive: null },
  ],
  [
    'lockfile at production not marked',
    edit('package-lock.json'),
    'Changed',
    null,
    [],
    [],
    { stakes: 'production', sensitive: null },
  ],
  [
    'lockfile at critical marked',
    edit('package-lock.json'),
    'Changed',
    null,
    [],
    [],
    { stakes: 'critical', sensitive: 'dependencies' },
  ],
  [
    'interlock marked',
    edit('firmware/interlock/pump.c'),
    'Changed',
    null,
    ['backend', 'reliability'],
    [],
    { stakes: 'critical', sensitive: 'safety or control logic' },
  ],
  [
    'interlock at production',
    edit('firmware/interlock/pump.c'),
    'Changed',
    null,
    ['backend'],
    ['reliability'],
    { stakes: 'production', sensitive: null },
  ],
  [
    'scada historian',
    edit('scada/historian/ingest.py'),
    'Changed',
    null,
    ['backend'],
    [],
    { stakes: 'critical', sensitive: 'safety or control logic' },
  ],
  [
    'grid substation',
    edit('energy/grid/substation/breaker.ts'),
    'Changed',
    null,
    ['backend'],
    [],
    { stakes: 'critical' },
  ],
  [
    'css grid is not energy',
    edit('src/components/Grid.tsx'),
    'Changed',
    null,
    ['ux'],
    ['backend', 'reliability'],
    { stakes: 'critical', sensitive: null },
  ],
  [
    'protected health information',
    edit('src/phi/redaction.ts'),
    'Changed',
    null,
    ['privacy'],
    [],
    { stakes: 'critical', sensitive: 'data retention or deletion' },
  ],
  [
    'phi in maths is not health data',
    edit('src/math/phi.ts'),
    'Changed',
    null,
    [],
    ['privacy'],
    { stakes: 'critical', sensitive: null },
  ],
  [
    'hl7 interface',
    edit('interfaces/hl7/adt_parser.py'),
    'Changed',
    null,
    ['data'],
    [],
    { stakes: 'critical' },
  ],
  [
    'mutex marked',
    edit('src/sync/mutex.rs'),
    'Changed',
    null,
    ['reliability'],
    [],
    { stakes: 'critical', sensitive: 'concurrency or transactions' },
  ],
  [
    'signing key marked',
    edit('src/crypto/sign.ts'),
    'Changed',
    null,
    ['security'],
    [],
    { stakes: 'critical', sensitive: 'cryptography or key management' },
  ],
  [
    'css overflow is not reliability',
    edit('src/styles/overflow.css'),
    'Changed',
    null,
    ['ux'],
    ['reliability'],
    { stakes: 'critical', sensitive: null },
  ],
  [
    'fuzzing harness',
    edit('fuzz/parse_fuzzer.rs'),
    'Changed',
    null,
    ['testing'],
    [],
    { stakes: 'critical' },
  ],
  [
    'formal model',
    edit('proofs/tla/replication_invariants.tla'),
    'Changed',
    null,
    ['reliability'],
    [],
    { stakes: 'critical' },
  ],
  [
    'audit log marked',
    edit('src/audit/auditLog.ts'),
    'Changed',
    null,
    ['privacy'],
    [],
    { stakes: 'critical', sensitive: 'audit logging' },
  ],
  [
    'lighthouse audit is not audit logging',
    edit('reports/lighthouse-audit.json'),
    'Changed',
    null,
    [],
    [],
    { stakes: 'critical', sensitive: null },
  ],
  [
    'realtime chat is not real-time systems',
    edit('src/realtime/chat.ts'),
    'Changed',
    null,
    [],
    ['performance'],
    { stakes: 'critical', sensitive: null },
  ],
];
module.exports = cases.map(([name, spec, stage, check, areas, not, opts = {}]) => ({
  name,
  tool: spec.tool,
  input: spec.input,
  response: spec.response,
  kind: spec.kind || 'PostToolUse',
  stage,
  check,
  areas,
  not,
  stakes: opts.stakes || 'standard',
  ...(Object.hasOwn(opts, 'sensitive') ? { sensitive: opts.sensitive } : {}),
}));
